server:
  port: 10010 # 端口号
spring:
  application:
    name: api-gateway # 服务名称
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka # 拉取服务的Eureka的地址
    registry-fetch-interval-seconds: 5 #  每5秒从Eureka更新一次信息
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    item-service: /item/** # 将商品微服务映射到/item/**
    search-service: /search/** # 将商品搜索微服务映射到/search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**

  add-host-header: true # 携带请求头本身的host头信息

  sensitive-headers: #禁止使用的头信息，设置为null，否则set-cookie无效

  ignored-services:
    - upload-service # 忽略upload-service服务
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms

ly:
  jwt:
    pubKeyPath: D:/itcast38/shiZhan/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item